# Generated by Django 3.0.2 on 2020-01-09 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.Marriage')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_calc.person_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Heir',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Person')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.person',),
        ),
        migrations.AddField(
            model_name='marriage',
            name='female',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='female', to='calc.Person'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='male', to='calc.Person'),
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Daughter',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='DaughterOfSon',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='GrandFather',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='GrandMother',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='MaternalHalfBrother',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='MaternalHalfSister',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='PaternalHalfBrother',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='PaternalHalfSister',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Sister',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='SonOfSon',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('heir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Heir')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.heir',),
        ),
        migrations.AddField(
            model_name='heir',
            name='calc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Calculation'),
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Person')),
                ('estate', models.IntegerField(default=1000)),
                ('calc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Calculation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('calc.person',),
        ),
    ]
