# Generated by Django 3.0.1 on 2019-12-23 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.Marriage')),
            ],
        ),
        migrations.AddField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husband', to='calc.Person'),
        ),
        migrations.AddField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wife', to='calc.Person'),
        ),
        migrations.CreateModel(
            name='Heir',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calc.Person')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Calculation')),
            ],
            bases=('calc.person',),
        ),
    ]
