# Generated by Django 3.0.1 on 2019-12-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Heir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heir_name', models.CharField(max_length=200)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Calculation')),
            ],
        ),
    ]
