# Generated by Django 3.0.2 on 2020-01-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heir',
            name='calc',
        ),
        migrations.AddField(
            model_name='father',
            name='calc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Calculation'),
        ),
    ]
