# Generated by Django 3.0.2 on 2020-03-20 15:42

import calc.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'base_manager_name': 'non_polymorphic'},
        ),
        migrations.AlterModelManagers(
            name='brother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daughter',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daughterofson',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deceased',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='father',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grandfather',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grandmother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='heir',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='husband',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='maternalhalfbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='maternalhalfsister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternalhalfbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternalhalfsister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='son',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofson',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wife',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='calculation',
            name='correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculation',
            name='exces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculation',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='shares_corrected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='shares_exces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heir',
            name='asaba',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heir',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heir',
            name='quote',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='heir',
            name='shared_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='calc',
            field=models.ForeignKey(null=True, on_delete=calc.models.NON_POLYMORPHIC_CASCADE, to='calc.Calculation'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='estate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='heir',
            name='calc',
            field=models.ForeignKey(null=True, on_delete=calc.models.NON_POLYMORPHIC_CASCADE, to='calc.Calculation'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='female',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='female', to='calc.Person'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='male', to='calc.Person'),
        ),
    ]
