# Generated by Django 3.0.2 on 2020-03-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20200320_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='quote_reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
