# Generated by Django 3.0.2 on 2020-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_heir_quote_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='correction',
            field=models.BooleanField(default=False),
        ),
    ]
