# Generated by Django 3.0.2 on 2020-03-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200323_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='exces',
            new_name='excess',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='shares_exces',
            new_name='shares_excess',
        ),
    ]
