# Generated by Django 3.0.2 on 2020-03-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20200325_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
