# Generated by Django 3.0.2 on 2020-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20200327_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='residual_shares',
            field=models.IntegerField(default=0),
        ),
    ]
