# Generated by Django 3.0.2 on 2020-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_calculation_residual_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='heir',
            name='shorted_share',
            field=models.IntegerField(default=0),
        ),
    ]
