# Generated by Django 3.0.2 on 2020-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20200330_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='shortage_calc_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heir',
            name='shortage_calc_share',
            field=models.IntegerField(default=0),
        ),
    ]
