# Generated by Django 3.0.2 on 2020-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20200330_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='shortage_union_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heir',
            name='shortage_union_shares',
            field=models.IntegerField(default=0),
        ),
    ]
