# Generated by Django 3.0.5 on 2020-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('calc', '0020_auto_20200420_1852'),
    ]

    operations = [
        migrations.RenameModel(
            new_name='PaternalHalfBrother',
            old_name='MaternalBrother',

        ),
        migrations.RenameModel(
            new_name='PaternalHalfSister',
            old_name='MaternalSister',
        ),
        migrations.RenameModel(
            new_name='MaternalHalfSister',
            old_name='PaternalBrother',
        ),
        migrations.RenameModel(
            new_name='MaternalHalfBrother',
            old_name='PaternalSister',
        ),
    ]
