# Generated by Django 3.0.5 on 2020-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('calc', '0020_correction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaternalHalfBrother',
            new_name='PaternalBrother',

        ),
        migrations.RenameModel(
            old_name='PaternalHalfSister',
            new_name='PaternalSister',
        ),
        migrations.RenameModel(
            old_name='MaternalHalfSister',
            new_name='MaternalSister',
        ),
        migrations.RenameModel(
            old_name='MaternalHalfBrother',
            new_name='MaternalBrother',
        ),
    ]
