# Generated by Django 3.0.5 on 2020-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('calc', '0019_paternaluncle_sonofbrother_sonofpaternalbrother_sonofpaternaluncle_sonofuncle_uncle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaternalHalfBrother',
            new_name='MaternalBrother',
        ),
        migrations.RenameModel(
            old_name='PaternalHalfSister',
            new_name='MaternalSister',
        ),
        migrations.RenameModel(
            old_name='MaternalHalfSister',
            new_name='PaternalBrother',
        ),
        migrations.RenameModel(
            old_name='MaternalHalfBrother',
            new_name='PaternalSister',
        ),
    ]
