# Generated by Django 5.2.8 on 2025-11-16 18:17

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0023_alter_person_polymorphic_ctype'),
    ]

    operations = [
        # First, update foreign keys that reference Person and Marriage so their
        # underlying column types are compatible with BigAutoField primary keys.
        migrations.AlterField(
            model_name='marriage',
            name='male',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='male_marriages',
                to='calc.person',
            ),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='female',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name='female_marriages',
                to='calc.person',
            ),
        ),
        migrations.AlterField(
            model_name='person',
            name='parents',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                to='calc.marriage',
            ),
        ),
        # Next, update foreign keys that reference Calculation so their column
        # types match the upcoming BigAutoField primary key.
        migrations.AlterField(
            model_name='deceased',
            name='calc',
            field=models.ForeignKey(
                null=True,
                on_delete=calc.models.NON_POLYMORPHIC_CASCADE,
                to='calc.calculation',
            ),
        ),
        migrations.AlterField(
            model_name='heir',
            name='calc',
            field=models.ForeignKey(
                null=True,
                on_delete=calc.models.NON_POLYMORPHIC_CASCADE,
                to='calc.calculation',
            ),
        ),
        # Then, promote the primary keys themselves to BigAutoField.
        migrations.AlterField(
            model_name='calculation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
