# Generated by Django 5.2.8 on 2025-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0023_alter_person_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
