# Generated by Django 4.2.28 on 2026-03-03 05:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_alter_calculation_id_alter_marriage_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='daughter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='daughterofson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deceased',
            options={},
        ),
        migrations.AlterModelOptions(
            name='father',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grandfather',
            options={},
        ),
        migrations.AlterModelOptions(
            name='grandmother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='heir',
            options={},
        ),
        migrations.AlterModelOptions(
            name='husband',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maternalbrother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maternalsister',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paternalbrother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paternalsister',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paternaluncle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sister',
            options={},
        ),
        migrations.AlterModelOptions(
            name='son',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sonofbrother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sonofpaternalbrother',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sonofpaternaluncle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sonofson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sonofuncle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uncle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={},
        ),
        migrations.AlterModelManagers(
            name='brother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daughter',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daughterofson',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deceased',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='father',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grandfather',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grandmother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='heir',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='husband',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='maternalbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='maternalsister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternalbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternalsister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternaluncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='son',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofpaternalbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofpaternaluncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofson',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofuncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='uncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wife',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
