# Generated by Django 5.2.17 on 2026-09-02 12:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0025_alter_brother_options_alter_daughter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='daughter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='daughterofson',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='deceased',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='father',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='grandfather',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='grandmother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='heir',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='husband',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='maternalbrother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='maternalsister',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='mother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paternalbrother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paternalsister',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paternaluncle',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sister',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='son',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sonofbrother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sonofpaternalbrother',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sonofpaternaluncle',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sonofson',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sonofuncle',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='uncle',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='brother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daughter',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='daughterofson',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='deceased',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='father',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grandfather',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grandmother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='heir',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='husband',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='maternalbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='maternalsister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternalbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternalsister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paternaluncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sister',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='son',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofpaternalbrother',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofpaternaluncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofson',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sonofuncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='uncle',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wife',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
